### ISSUE TITLE
FolderListView.qml - ReferenceError: units is not defined

### ISSUE THREAD

**Issue by justintime4tea** [papyros/files-app#10]
#### Issue Description:

When attempting to run **files-app** I get a "not defined" error for "units"

</br>
#### Application stdout:

```
qml/components/FolderListView.qml:45: ReferenceError: units is not defined
qml/components/FolderListView.qml:55: ReferenceError: units is not defined
qml/components/FolderListView.qml:54: ReferenceError: units is not defined
qml/components/FolderListView.qml:67: ReferenceError: units is not defined
qml/components/FolderListView.qml:75: ReferenceError: units is not defined
qml/components/FolderListView.qml:51: ReferenceError: units is not defined
qml/components/FolderListView.qml:106: ReferenceError: units is not defined
```

</br>
#### Potential Fix:

Changing "units" to "Units" in the above listed files (simply capitalizing the U) fixes the reference error.
This was most likely due to either a library change (less likely) or mistake when referencing units (not capitalizing, more likely)

_Fixing in my fork and submitting pull-request_

**Comment by ricardomv** [comment]
Fixed in #12
