### ISSUE TITLE
"org.nemomobile.folderlistmodel" is not installed

### ISSUE THREAD

**Issue by ghost** [papyros/files-app#20]
It's installed successfully but when I launch it it tells me:
`QQmlApplicationEngine failed to load component
file:///usr/local/share/papyros-files/qml/main.qml:23 module "org.nemomobile.folderlistmodel" is not installed` <br/>
I tried installing https://code.launchpad.net/~ajalkane/ubuntu-filemanager-app/qml-folderlistmodel <br/>
but that doesn't change anything. what do?

**Comment by ricardomv** [comment]
What distro do you use? org.nemomobile.folderlistmodel is installed with the app i think the issue here is that you didn't pass cmake the install prefix with `cmake -DCMAKE_INSTALL_PREFIX=/usr .`

**Comment by ghost** [comment]
I'm using fedora 22
I'll try passing that and will update you with results

**Comment by ghost** [comment]
unfortunately it's the same error

**Comment by ghost** [comment]
the output of sudo make install

```
[adam@macbook build] (master)$ sudo make install
[sudo] password for adam: 
[  2%] Built target translations
[  5%] Automatic moc for target nemofolderlistmodel
[  5%] Built target nemofolderlistmodel_automoc
[ 62%] Built target nemofolderlistmodel
[ 65%] Automatic moc for target PlacesModel
[ 65%] Built target PlacesModel_automoc
[ 77%] Built target PlacesModel
[ 80%] Automatic moc for target Archives
[ 80%] Built target Archives_automoc
[ 90%] Built target Archives
[ 92%] Automatic moc for target papyros-files
[ 92%] Built target papyros-files_automoc
[100%] Built target papyros-files
[100%] Built target papyros-files-qmlfiles
Install the project...
-- Install configuration: ""
-- Installing: /usr/share/applications/io.papyros.files.desktop
-- Installing: /usr/share/papyros-files/translations/pt_PT.qm
-- Installing: /org/nemomobile/folderlistmodel/libnemofolderlistmodel.so
-- Up-to-date: /org/nemomobile/folderlistmodel/qmldir
-- Installing: /com/ubuntu/PlacesModel/libPlacesModel.so
-- Up-to-date: /com/ubuntu/PlacesModel/qmldir
-- Installing: /com/ubuntu/Archives/libArchives.so
-- Up-to-date: /com/ubuntu/Archives/qmldir
-- Installing: /usr/share/papyros-files/qml
-- Installing: /usr/share/papyros-files/qml/SelectionPage.qml
-- Installing: /usr/share/papyros-files/qml/TrashPage.qml
-- Installing: /usr/share/papyros-files/qml/FolderPage.qml
-- Installing: /usr/share/papyros-files/qml/components
-- Installing: /usr/share/papyros-files/qml/components/SelectionListItem.qml
-- Installing: /usr/share/papyros-files/qml/components/FileListItem.qml
-- Installing: /usr/share/papyros-files/qml/components/InfoSidebar.qml
-- Installing: /usr/share/papyros-files/qml/components/PlacesSidebar.qml
-- Installing: /usr/share/papyros-files/qml/components/FolderListView.qml
-- Installing: /usr/share/papyros-files/qml/main.qml
-- Installing: /usr/share/papyros-files/qml/backend
-- Installing: /usr/share/papyros-files/qml/backend/FolderModel.qml
-- Installing: /usr/bin/papyros-files
```

so yeah it does install it, I don't know what's wrong :/

**Comment by ghost** [comment]
I noticed that's it's looking for it in /usr/local/share, so I changed the prefix to `-DCMAKE_INSTALL_PREFIX=/usr/local` so that it would match the location it's looking into, but still gives the same error. I'm really confused :/

**Comment by ricardomv** [comment]
clean the build directory and all the installed files (including in /usr/local) and build with `DCMAKE_INSTALL_PREFIX=/usr`

**Comment by ghost** [comment]
deleted the following:

```
/usr/bin/papyros-files
/usr/share/Applications/io.papyros.files.desktop
/usr/share/papyros-files/
/org/
/com/
```

deleted the build directory and created it again. <br/>
`cd build`
`cmake DCMAKE_INSTALL_PREFIX=/usr ..`
`make`
`sudo make install`

and then I tried to run the app, but I still get the same answer:

```
[adam@macbook build] (master)$ papyros-files
QQmlApplicationEngine failed to load component
file:///usr/local/share/papyros-files/qml/main.qml:23 module "org.nemomobile.folderlistmodel" is not installed
```

but why is libnemofolderlistmodel.so installed into /org/nemomobile/folderlistmodel/libnemofolderlistmodel.so? <br/>
and why are some stuff installed into /com/? I guess that's the problem.

**Comment by ricardomv** [comment]
You need to delete the binary in /usr/local  and everything you installed without the cmake flag including that folder /org/nemomobile

**Comment by ghost** [comment]
I swear to God I did :D

---- Ricardo Vieira wrote ----

You need to delete the binary in /usr/local  and everything you installed without the cmake flag including that folder /org/nemomobile

---

**Comment by ricardomv** [comment]
@lordadamson `cmake DCMAKE_INSTALL_PREFIX=/usr ..` did you miss the "-" before the D

**Comment by ghost** [comment]
I cleaned everything again just in case I forgot that "-" before the D.
but unfortunately that was no good.
I still receive the same error

**Comment by iBelieve** [comment]
Try adding `-DQML_INSTALL_DIR=lib/qt/qml` (in addition to the `usr` install prefix). That seems to be necessary for the shell, so it may be needed here as well.

**Comment by ghost** [comment]
it gave me that warning when cmaking

```
CMake Warning:
  Manually-specified variables were not used by the project:

    QML_INSTALL_DIR
```

and then the same error when I try to run:

```
[adam@macbook build] (master)$ papyros-files
QQmlApplicationEngine failed to load component
file:///usr/share/papyros-files/qml/main.qml:23 module "org.nemomobile.folderlistmodel" is not installed

```

**Comment by iBelieve** [comment]
Ah, ok. That must be a custom variable we're using in the shell then.

**Comment by ghost** [comment]
well I don't really understand what to do now :D

**Comment by ricardomv** [comment]
@lordadamson what is the output of `qmake -query QT_INSTALL_QML`

**Comment by ghost** [comment]
`/usr/lib64/qt5/qml`

by the way... I'd like to thank you for not getting pissed the hell off of my issue :) so yeah, thanks for your patience.

**Comment by demmm** [comment]
Encountered the same issue here, fixed it with:
`sed -i -e 's|qmake -query QT_INSTALL_QML|qmake-qt5 -query QT_INSTALL_QML|' ${pkgname}/CMakeLists.txt`

**Comment by ricardomv** [comment]
@demmm This is a good addition that drops the dependencie of qtchooser

**Comment by ghost** [comment]
unfortunately that doesn't solve the issue for me. however it does change the error message.

```
[adam@macbook build] (master)$ papyros-files 
QQmlApplicationEngine failed to load component
file:///usr/share/papyros-files/qml/main.qml:33 Type FolderPage unavailable
file:///usr/share/papyros-files/qml/FolderPage.qml:75 Type FolderListView unavailable
file:///usr/share/papyros-files/qml/components/FolderListView.qml:96 ListItem.Subheader is not a type
```

**Comment by ricardomv** [comment]
@lordadamson do you have the latest version of qml-material installed?

**Comment by ricardomv** [comment]
@lordadamson any news?
