### ISSUE TITLE
Add uninstall target to cmake

### ISSUE THREAD

**Issue by deadbaed** [papyros/files-app#26]
how to uninstall the app? `sudo make uninstall` doesn't work :(

**Comment by ricardomv** [comment]
Added in 14bebf7f Can you check if it works for you?

**Comment by deadbaed** [comment]
it works! thank you!

![screenshot from 2015-11-07 18-27-30](https://cloud.githubusercontent.com/assets/8809909/11016303/40877a92-857d-11e5-974b-d82959000619.png)
