### ISSUE TITLE
Add support for keyboard bindings

### ISSUE THREAD

**Issue by chaitan94** [papyros/files-app#29]
Keyboard bindings would certainly make the application a lot more usable.
Some of the common/basic functionalities could be:

| Shortcut | Description |
| --- | --- |
| Up, Down arrows | move to certain file/directory in the current list |
| Return | Open the currently selected directory |
| Alt + Left Arrow | Move back to previous directory |
| Alt + Right Arrow | Undo a move back action |
| Alt + Up Arrow | Move one directory up in the hierarchy |
| Backspace | Alias for Alt + Left Arrow |
| Ctrl + N | New Window |
| Ctrl + Shift + N | New Folder in current directory |

Of course there are many other such shortcuts possible like cut, copy, paste, rename, select all, close window etc.

Also, If a alphanumeric string is being typed, move selection to the first folder with that string as prefix

**Comment by f1recracker** [comment]
+1

**Comment by ricardomv** [comment]
Most of the shortcuts have been added and others need new features to be implemented, so i'm closing this issue and adding the features to the todo list. Thanks for your help.
