### ISSUE TITLE
github version fails to compile on arch

### ISSUE THREAD

**Issue by ctnlaring** [papyros/files-app#5]
cmake .. runs successfully but when I run make I get:

$ make
[  2%] Merging translations into io.papyros.files.desktop...
/bin/sh: INTLTOOL_MERGE-NOTFOUND: command not found
CMakeFiles/io.papyros.files.desktop.dir/build.make:49: recipe for target 'CMakeFiles/io.papyros.files.desktop' failed
make[2]: **\* [CMakeFiles/io.papyros.files.desktop] Error 127
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/io.papyros.files.desktop.dir/all' failed
make[1]: **\* [CMakeFiles/io.papyros.files.desktop.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by ricardomv** [comment]
you need to install `intltool` to get it to work, we should add it to the dependencies.
