### ISSUE TITLE
FirstListItem.qml - ReferenceError: units is not defined

### ISSUE THREAD

**Issue by justintime4tea** [papyros/files-app#8]
#### Issue Description:

When attempting to run **files-app** I get a "not defined" error for "units"

</br>
#### Application stdout:

```
qml: inode/directory
qml/components/FileListItem.qml:51: ReferenceError: units is not defined
qml/components/FileListItem.qml:50: ReferenceError: units is not defined
qml/components/FileListItem.qml:55: ReferenceError: units is not defined
qml/components/FileListItem.qml:66: ReferenceError: units is not defined
```

</br>
#### Potential Fix:

Changing "units" to "Units" in the above listed files (simply capitalizing the U) fixes the reference error.
This was most likely due to either a library change (less likely) or mistake when referencing units (not capitalizing, more likely)

_Fixing in my fork and submitting pull-request_

**Comment by ricardomv** [comment]
Fixed in #12
